sudo: yes
dist: xenial

language: python

cache: pip

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - name: Requirements
      env: TOXENV=requirements
      python: "3.5"
      addons: null
      before_script: null
    - name: Coding Style
      env: TOXENV=style
      python: "3.5"
      addons: null
      before_script: null
    - name: Sanitizer Configuration
      env: TOXENV=sanitizer
      python: "3.5"
      addons: null
      before_script: null


addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4

install: pip install tox-travis

before_script: psql -U postgres -c "create extension postgis"

script: tox

after_success: pip install -r requirements-cov.txt && codecov
