# Postgis doesn't work on older 'precise' platform
# and the default depends on repo age (parkkihubi is too old)
sudo: false
dist: trusty

language: python

cache: pip

matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - env: TOXENV=requirements
      python: "3.4"
      addons: null
      before_script: null
    - env: TOXENV=style
      python: "3.4"
      addons: null
      before_script: null


# As of 2017-08 the new travis trusty images have broken postgis,
# so we have to specify the exact postgres version to install right addons
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

install: pip install tox-travis codecov

before_script: psql -U postgres -c "create extension postgis"

script: tox

after_success: codecov
