# Postgis doesn't work on older 'precise' platform
# and the default depends on repo age (parkkihubi is too old)
sudo: false
dist: trusty

language: python
python:
  - '3.6'
  - 'nightly'

cache: pip

services:
  - postgresql

install: 'pip install codecov -r requirements.txt -r requirements-dev.txt'

before_script:
  - psql -c 'create database parkkihubi;' -U postgres
  - psql -U postgres -c "create extension postgis"

script:
  - flake8
  - pytest -ra -vvv --cov

after_success: codecov

env:
  - SECRET_KEY=topsecret123
