sudo: yes
dist: xenial

language: python

cache: pip

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - env: TOXENV=requirements
      python: "3.5"
      addons: null
      before_script: null
    - env: TOXENV=style
      python: "3.5"
      addons: null
      before_script: null


addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4

install: pip install tox-travis codecov

before_script: psql -U postgres -c "create extension postgis"

script: tox

after_success: codecov
