version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: parkkihubi
      POSTGRES_USER: parkkihubi
      POSTGRES_PASSWORD: parkkihubi
      PGDATABASE: parkkihubi
      PGUSER: parkkihubi
      PGPASSWORD: parkkihubi
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    platform: "linux/amd64"
    image: parkkihubi
    build:
      context: "."
      target: "development"
    environment:
      DATABASE_URL: postgis://parkkihubi:parkkihubi@db/parkkihubi
      RUN_MIGRATIONS: 1
      DEBUG: 1
      SECRET_KEY: not-empty
      VAR_ROOT: /tmp/var
    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:5678:5678"
    volumes:
      - .:/app

volumes:
  db_data:
