#!/bin/bash
set -e

if [[ "${1:0:1}" = "/" ]]; then
    exec "$@"
fi

PORT=${DJANGO_PORT:-8000}
DEBUG_PORT=${DEBUGPY_PORT:-5678}

RUN_MODE=${RUN_MODE:-development}
RUN_MIGRATIONS=${RUN_MIGRATIONS}

if [[ $RUN_MIGRATIONS != "0" ]]; then
    ./manage.py migrate --noinput
fi

if [[ $RUN_COLLECT_STATIC != "0" ]]; then
    ./manage.py collectstatic --noinput
fi

if [[ "$RUN_MODE" == "debug" ]]; then
    if ! [ -d /tmp/debugpy ]; then
        pip --disable-pip-version-check install debugpy -t /tmp
    fi
    echo "Starting Django to port $PORT with debugpy on port $DEBUG_PORT..."
    python /tmp/debugpy --wait-for-client --listen 0.0.0.0:$DEBUG_PORT \
        manage.py runserver 0.0.0.0:$PORT --nothreading --noreload
elif [[ -n "$1" ]]; then
    ./manage.py "$@"
elif [[ "$RUN_MODE" == "production" ]]; then
    uwsgi \
        --plugin python3 \
        --need-app \
        --wsgi parkkihubi.wsgi \
        --http-socket :$PORT \
        --static-map /static=/app/var/static \
        --master \
        --enable-threads \
        --workers 4 \
        --die-on-term \
        --single-interpreter \
        --thunder-lock \
        --ignore-sigpipe \
        --ignore-write-errors \
        --disable-write-exception
else
    ./manage.py runserver 0.0.0.0:$PORT
fi
