#!/bin/bash
set -e

if [[ "${1:0:1}" = "/" ]]; then
    exec "$@"
fi

PORT=${DJANGO_PORT:-8000}
DEBUG_PORT=${DEBUGPY_PORT:-5678}

RUN_MODE=${RUN_MODE:-development}

if [[ "$RUN_MODE" == "debug" ]]; then
    if ! [[ -d /tmp/debugpy ]]; then
        pip --disable-pip-version-check install debugpy -t /tmp
    fi
    echo "Using debugpy on port $DEBUG_PORT..."
    prefix_cmd=(
        python /tmp/debugpy --wait-for-client --listen 0.0.0.0:$DEBUG_PORT
    )
    default_cmd=(runserver 0.0.0.0:$PORT --nothreading --noreload)
    RUN_MIGRATIONS=${RUN_MIGRATIONS:-0}
    RUN_COLLECT_STATIC=${RUN_COLLECT_STATIC:-0}
else
    prefix_cmd=()
    default_cmd=(runserver 0.0.0.0:$PORT)
fi

if [[ $RUN_MIGRATIONS != "0" ]]; then
    ./manage.py migrate --noinput
fi

if [[ $RUN_COLLECT_STATIC != "0" ]]; then
    ./manage.py collectstatic --noinput
fi

if [[ -n "$1" ]]; then
    "${prefix_cmd[@]}" ./manage.py "$@"
elif [[ "$RUN_MODE" == "production" ]]; then
    uwsgi \
        --need-app \
        --venv "$VIRTUALENV" \
        --wsgi parkkihubi.wsgi \
        --http-socket :$PORT \
        --static-map /static=/home/appuser/var/static \
        --master \
        --enable-threads \
        --workers 4 \
        --die-on-term \
        --py-call-uwsgi-fork-hooks \
        --single-interpreter \
        --thunder-lock \
        --ignore-sigpipe \
        --ignore-write-errors \
        --disable-write-exception
else
    "${prefix_cmd[@]}" ./manage.py "${default_cmd[@]}"
fi
