#!/bin/sh

set -e

docs="
api/enforcement
api/operator
api/public
"

docs_dir=$(cd "$(dirname "$0")" && pwd)/docs
generator_dir=$docs_dir/doc-generator
openapi=$generator_dir/node_modules/.bin/openapi

default_output_dir=$docs_dir/generated

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    echo "Usage: $0 [OUTPUT_DIR]"
    echo "       $0 [-h|--help]"
    exit 0
fi

if [ -n "$1" ]; then
    output_dir=$1
else
    output_dir=$default_output_dir
fi

if [ ! -e "$openapi" ]; then
    echo "Installing @redocly/cli for the \"openapi\" tool"
    old_dir=$(pwd)
    cd "$generator_dir"
    NODE_ENV=production yarn
    cd "$old_dir"
    echo
fi

for name in $docs; do
    echo "Generating $name documentation"
    "$openapi" build-docs "$docs_dir/$name.yaml" -o "$output_dir/$name/index.html"
    echo
done

echo "Documentation generated to $output_dir"
