#!/bin/sh
set -e

pip install prequ==1.3.1
prequ sync requirements.txt
./manage.py collectstatic --noinput
./manage.py migrate --noinput

if [ -x ../bin/update-notify ]; then
    ../bin/update-notify "Succesfully updated to $new_ver"
fi
