[tox]
envlist = py{310},uvlock,style,sanitizer
skipsdist = True

[testenv]
runner = uv-venv-lock-runner
no_default_groups = true
dependency_groups = dev
passenv = CI
setenv =
    DEBUG=0
    SECRET_KEY=topsecret123
commands =
    pytest -ra -vvv --strict --doctest-modules \
    {posargs:--cov=. --cov-report=term --cov-report=xml}

[testenv:uvlock]
basepython = python3.10
dependency_groups =
commands = uv lock --check

[testenv:style]
basepython = python3.10
dependency_groups = style
commands = flake8 {posargs:--enable=T}

[testenv:sanitizer]
basepython = python3.10
dependency_groups =
commands = python ./manage.py check_sanitizerconfig

[gh-actions]
python =
    3.10: py310
