[tox]
envlist =
    py310-django{42,52}
    py312-django{42,52,60}
    py314-django{52,60}
    py312-django52-locked
    uvlock
    style
    check
    sanitizer
labels =
    check = uvlock, style, check, sanitizer
basepython = python3.12

[testenv]
labels =
    py3{10,12,14}: test
package = deps-only
runner = uv-venv-runner
constrain_package_deps = True
no_default_groups = true
dependency_groups =
    dev
    deploy
passenv = CI
deps =
    django42: django~=4.2.0
    django52: django~=5.2.0
    django60: django~=6.0.0
setenv =
    DEBUG=0
    SECRET_KEY=not-very-secret-but-long-enough-to-avoid-Warnings.123
commands =
    pytest -ra -vvv --strict --doctest-modules \
    {posargs:--cov=. --cov-report=term --cov-report=xml}

[testenv:py312-django52-locked]
package = skip
runner = uv-venv-lock-runner

[testenv:uvlock]
package = skip
dependency_groups =
commands = uv lock --check

[testenv:style]
package = skip
dependency_groups = style
commands = flake8 {posargs:--enable=T}

[testenv:check]
package = skip
runner = uv-venv-lock-runner
dependency_groups =
commands = python ./manage.py check

[testenv:sanitizer]
package = skip
runner = uv-venv-lock-runner
dependency_groups =
commands = python ./manage.py check_sanitizerconfig

[gh-actions]
python =
    3.10: py310
    3.12: py312
    3.14: py314
