# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 12:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_translatable_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='device_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='device identifier'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='location'),
        ),
    ]
