# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 08:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0003_parking_device_id_and_location_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='external ID')),
                ('areas', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3879, verbose_name='areas')),
                ('space_amount_estimate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='space amount estimate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
