# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0004_add_parking_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parking_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkings.ParkingArea', verbose_name='parking area'),
        ),
    ]
