# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0005_add_parking_area_to_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='device_identifier',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='resident_code',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='special_code',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
