# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 12:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0006_remove_obsolete_stuff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingarea',
            options={'verbose_name': 'parking area', 'verbose_name_plural': 'parking areas'},
        ),
        migrations.RenameField(
            model_name='parkingarea',
            old_name='external_id',
            new_name='origin_id',
        ),
        migrations.RenameField(
            model_name='parkingarea',
            old_name='areas',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='parkingarea',
            old_name='space_amount_estimate',
            new_name='capacity_estimate',
        ),
    ]
