# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 08:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0007_rename_parking_area_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingarea',
            name='capacity_estimate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='capacity estimate'),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3879, verbose_name='geometry'),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='origin_id',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='origin ID'),
        ),
    ]
