# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0008_fix_some_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='registration number'),
        ),
    ]
