# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0009_disable_registration_number_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='time_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='parking end time'),
        ),
    ]
