# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0010_change_time_end_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='parking_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parkings', to='parkings.ParkingArea', verbose_name='parking area'),
        ),
    ]
