# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:42
from __future__ import unicode_literals

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0011_add_parking_area_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingTerminal',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(
                    auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(
                    default=uuid.uuid4, editable=False,
                    primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(
                    unique=True, verbose_name='number')),
                ('name', models.CharField(
                    max_length=200, verbose_name='name')),
                ('location', django.contrib.gis.db.models.fields.PointField(
                    blank=True, null=True, srid=4326, verbose_name='location')),
            ],
            options={
                'verbose_name': 'parking terminal',
                'verbose_name_plural': 'parking terminals',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='parking',
            name='terminal_number',
            field=models.CharField(
                blank=True, max_length=50, verbose_name='terminal number'),
        ),
        migrations.AddField(
            model_name='parking',
            name='terminal',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='parkings.ParkingTerminal', verbose_name='terminal'),
        ),
    ]
