# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 02:22
from __future__ import unicode_literals

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0016_normalized_reg_num_noblank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(
                    auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(
                    default=uuid.uuid4, editable=False,
                    primary_key=True, serialize=False)),
                ('name', models.CharField(
                    blank=True, max_length=200, verbose_name='name')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(
                    srid=3879, verbose_name='geometry')),
            ],
            options={
                'verbose_name_plural': 'regions',
                'verbose_name': 'region',
            },
        ),
        migrations.AddField(
            model_name='parkingarea',
            name='region',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='areas',
                to='parkings.Region', verbose_name='region'),
        ),
    ]
