# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-22 08:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0020_add_paymentzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('identifier', models.CharField(max_length=10, verbose_name='identifier')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3879, verbose_name='geometry')),
            ],
            options={
                'ordering': ('identifier',),
            },
        ),
    ]
