# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-24 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0021_add_permitarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentzone',
            name='number',
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3)
                ],
                verbose_name='zone number'),
        ),
        migrations.AlterField(
            model_name='permitarea',
            name='identifier',
            field=models.CharField(
                max_length=10, unique=True, verbose_name='identifier'),
        ),
    ]
