# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parkings', '0022_unique_area_identifiers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermitCacheItem', new_name='PermitLookupItem'),
        migrations.AlterField(
            model_name='permitlookupitem', name='permit',
            field=models.ForeignKey(
                to='parkings.Permit', on_delete=models.CASCADE,
                related_name='lookup_items')),
    ]
