# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parkings', '0023_permitlookupitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitlookupitem',
            options={
                'ordering': ('registration_number', 'start_time', 'end_time')
            },
        ),
        migrations.AddIndex(
            model_name='permitlookupitem',
            index=models.Index(
                fields=[
                    'registration_number', 'start_time', 'end_time',
                    'area_identifier', 'permit'],
                name='parkings_pe_registr_84b475_idx'),
        ),
    ]
