# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 07:49
from __future__ import unicode_literals

from django.contrib.gis.db.models.fields import PointField
from django.contrib.postgres.fields.jsonb import JSONField
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parkings', '0024_permitlookupitem_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCheck',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True, verbose_name='time created')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('time_overridden', models.BooleanField(
                    verbose_name='time was overridden')),
                ('registration_number', models.CharField(
                    max_length=20, verbose_name='registration number')),
                ('location', PointField(
                    srid=4326, verbose_name='location')),
                ('result', JSONField(
                    blank=True,
                    encoder=DjangoJSONEncoder,
                    verbose_name='result')),
                ('allowed', models.BooleanField(
                    verbose_name='parking was allowed')),
                ('found_parking', models.ForeignKey(
                    to='parkings.Parking', on_delete=models.SET_NULL,
                    blank=True, null=True, verbose_name='found parking')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'verbose_name': 'parking check',
                'verbose_name_plural': 'parking checks'
            },
        ),
    ]
