# Generated by Django 2.2.3 on 2019-07-18 06:34

from django.conf import settings
from django.db import migrations, models


def fill_parkingcheck_performer(apps, schema_editor):
    parking_check_model = apps.get_model('parkings', 'ParkingCheck')
    items_to_process = parking_check_model.objects.filter(performer=None)

    if not items_to_process.exists():
        return

    # Find a user, or create one if none exists
    user_model = apps.get_model(settings.AUTH_USER_MODEL)
    user = user_model.objects.filter(is_superuser=True).first()
    if not user:
        user = user_model.objects.first()
        if not user:
            user = user_model.objects.create_user(
                username='dummy', email='', password=None)

    # Update the performer field to the found or created user
    items_to_process.update(performer=user)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkings', '0026_fix_permit_regnum_length'),
    ]

    operations = [
        migrations.AddField(  # Add the field as nullable
            model_name='parkingcheck',
            name='performer',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.PROTECT,
                editable=False,
                null=True,
                blank=True,
                verbose_name='performer',
                help_text='User who performed the check')),
        migrations.RunPython(  # Fill the field for existing rows
            code=fill_parkingcheck_performer,
            reverse_code=migrations.RunPython.noop),
        migrations.AlterField(  # Set the field to non-nullable
            model_name='parkingcheck',
            name='performer',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.PROTECT,
                editable=False,
                verbose_name='performer',
                help_text='User who performed the check')),
    ]
