# Generated by Django 2.2.8 on 2020-01-31 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("parkings", "0028_digital_disc_changes")]

    operations = [
        migrations.CreateModel(
            name="ParkingCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(db_index=True, verbose_name="time")),
                (
                    "is_forecast",
                    models.BooleanField(default=False, verbose_name="is forecast"),
                ),
                ("number", models.IntegerField(verbose_name="number")),
                (
                    "parking_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_counts",
                        to="parkings.ParkingArea",
                        verbose_name="parking area",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_counts",
                        to="parkings.Region",
                        verbose_name="region",
                    ),
                ),
            ],
            options={
                "unique_together": {("time", "region", "parking_area", "is_forecast")}
            },
        )
    ]
