# Generated by Django 2.2.8 on 2020-01-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0029_enforcementdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentzone',
            name='code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentzone',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parkings.EnforcementDomain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permit',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='parkings.EnforcementDomain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentzone',
            name='number',
            field=models.IntegerField(verbose_name='zone number'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentzone',
            unique_together={('domain', 'code')},
        ),
    ]
