# Generated by Django 2.2.8 on 2020-02-03 13:00

from django.db import migrations, models


def _generate_area_ids(apps, schema_editor):
    permit_area_model = apps.get_model('parkings', 'PermitArea')
    for index, permit in enumerate(permit_area_model.objects.all(), start=1):
        permit.tmp_id = index
        permit.save(update_fields=['tmp_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0029_alter_payment_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitarea',
            name='tmp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(_generate_area_ids, migrations.RunPython.noop),
        migrations.RemoveField('permitarea', 'id'),
        migrations.AlterField(
            model_name='permitarea',
            name='tmp_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='permitarea',
            old_name='tmp_id',
            new_name='id'
        ),
    ]
