# Generated by Django 2.2.8 on 2020-02-03 13:48

from django.db import migrations, models
import django.db.models.deletion


def _add_area(apps, schema_editor):
    permit_area_model = apps.get_model('parkings', 'PermitArea')
    permit_lookup_item = apps.get_model('parkings', 'PermitLookupItem')
    for permit in permit_lookup_item.objects.all():
        permit.area = permit_area_model.objects.get(identifier=permit.area_identifier)
        permit.save(update_fields=['area'])


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0032_alter_permit_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitlookupitem',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkings.PermitArea'),
        ),
        migrations.RunPython(_add_area, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='permitlookupitem',
            name='parkings_pe_registr_84b475_idx',
        ),
        migrations.RemoveField(
            model_name='permitlookupitem',
            name='area_identifier',
        ),
        migrations.AddIndex(
            model_name='permitlookupitem',
            index=models.Index(fields=['registration_number', 'start_time', 'end_time', 'area', 'permit'], name='parkings_pe_registr_2f5bf5_idx'),
        ),
    ]
