# Generated by Django 2.2.8 on 2020-01-16 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0032_domain_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enforcer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_areas', to='parkings.EnforcementDomain'),
        ),
        migrations.AlterField(
            model_name='parkingterminal',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_terminals', to='parkings.EnforcementDomain'),
        ),
        migrations.AlterField(
            model_name='paymentzone',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_zones', to='parkings.EnforcementDomain'),
        ),
        migrations.AlterField(
            model_name='paymentzone',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='permit',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='parkings.EnforcementDomain'),
        ),
        migrations.AlterField(
            model_name='permitarea',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_areas', to='parkings.EnforcementDomain'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentzone',
            unique_together={('domain', 'code')},
        ),
        migrations.AlterField(
            model_name='permitseries',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='permitarea',
            name='permitted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='permitted_user'),
        ),
        migrations.AlterField(
            model_name='permitlookupitem',
            name='area_identifier',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
    ]
