# Generated by Django 2.2.8 on 2020-02-03 13:48

from django.db import migrations, models
import django.db.models.deletion


def _fill_area_fks(apps, schema_editor):
    permit_area_model = apps.get_model('parkings', 'PermitArea')
    permit_lookup_item = apps.get_model('parkings', 'PermitLookupItem')
    for permit_area in permit_area_model.objects.all():
        items = permit_lookup_item.objects.filter(area_identifier=permit_area.identifier)
        items.update(area=permit_area)


def _fill_area_identifiers(apps, schema_editor):
    permit_area_model = apps.get_model('parkings', 'PermitArea')
    permit_lookup_item = apps.get_model('parkings', 'PermitLookupItem')
    for permit_area in permit_area_model.objects.all():
        items = permit_lookup_item.objects.filter(area=permit_area)
        items.update(area_identifier=permit_area.identifier)


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0033_default_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitlookupitem',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='parkings.PermitArea'),
        ),
        migrations.RunPython(_fill_area_fks, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='permitlookupitem',
            name='parkings_pe_registr_84b475_idx',
        ),
        migrations.RunPython(migrations.RunPython.noop, _fill_area_identifiers),
        migrations.RemoveField(
            model_name='permitlookupitem',
            name='area_identifier',
        ),
        migrations.AddIndex(
            model_name='permitlookupitem',
            index=models.Index(fields=['registration_number', 'start_time', 'end_time', 'area', 'permit'], name='parkings_pe_registr_2f5bf5_idx'),
        ),
    ]
