# Generated by Django 2.2.10 on 2020-04-15 11:41

import django.db.models.deletion
from django.db import migrations, models

from parkings.models import PaymentZone


def _generate_missing_payment_zone(apps, schema_editor):
    if PaymentZone.objects.exists():
        other_zone = PaymentZone.objects.order_by('number').last()
        PaymentZone.objects.get_or_create(
            id=3,
            defaults=dict(
                domain=other_zone.domain,
                code='3',
                number=3,
                name="Automatically generated PaymentZone",
                geom=other_zone.geom,
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0034_permitlookupitem_area'),
    ]

    operations = [
        migrations.RunPython(_generate_missing_payment_zone, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='parking',
            name='zone',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='parkings',
                to='parkings.PaymentZone',
                verbose_name='PaymentZone'
            ),
        ),
    ]
