# Generated by Django 2.2.12 on 2020-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0039_archivedparking_sanitized_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingterminal',
            name='number',
            field=models.CharField(max_length=200, unique=True, verbose_name='number'),
        ),
    ]
