# Generated by Django 2.2.15 on 2022-05-14 06:07

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0040_alter_parkingterminal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='properties'),
        ),
    ]
