# Generated by Django 2.2.15 on 2022-12-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkings", "0041_permit_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedparking",
            name="archived_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="time archived"
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="time created"
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="domain",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archived_parkings",
                to="parkings.EnforcementDomain",
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="modified_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="time modified"
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="normalized_reg_num",
            field=models.CharField(
                max_length=20, verbose_name="normalized registration number"
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="operator",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archived_parkings",
                to="parkings.Operator",
                verbose_name="operator",
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="parking_area",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_parkings",
                to="parkings.ParkingArea",
                verbose_name="parking area",
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="region",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_parkings",
                to="parkings.Region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="registration_number",
            field=models.CharField(max_length=20, verbose_name="registration number"),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_parkings",
                to="parkings.ParkingTerminal",
                verbose_name="terminal",
            ),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="time_start",
            field=models.DateTimeField(verbose_name="parking start time"),
        ),
        migrations.AlterField(
            model_name="archivedparking",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archived_parkings",
                to="parkings.PaymentZone",
                verbose_name="PaymentZone",
            ),
        ),
    ]
