# Generated by Django 2.2.15 on 2023-04-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkings", "0042_archive_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermitSubjectItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("registration_number", models.CharField(max_length=20)),
                (
                    "permit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_items",
                        to="parkings.Permit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermitAreaItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parkings.PermitArea",
                    ),
                ),
                (
                    "permit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_items",
                        to="parkings.Permit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="permitlookupitem",
            name="area_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lookup_items",
                to="parkings.PermitAreaItem",
            ),
        ),
        migrations.AddField(
            model_name="permitlookupitem",
            name="subject_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lookup_items",
                to="parkings.PermitSubjectItem",
            ),
        ),
    ]
