# Generated by Django 2.2.15 on 2022-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0044_populate_permit_items_from_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingarea',
            name='name',
            field=models.CharField(
                blank=True, default='', max_length=200, verbose_name='name'),
        ),
    ]
