# Generated by Django 2.2.15 on 2023-11-23 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parkings", "0045_parkingarea_name"),
    ]

    operations = [
        # Allow null values temporarily to make the migrations
        # reversible  (the field will be removed in the following
        # migrations so it doesn't matter for the forward direction)
        migrations.AlterField(
            model_name="permitarea",
            name="permitted_user",
            field=models.ForeignKey(
                on_delete=models.SET_NULL,
                null=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="permitted_user",
            ),
        ),

        # Add the new field
        migrations.AddField(
            model_name="permitarea",
            name="allowed_users",
            field=models.ManyToManyField(
                help_text="Users who are allowed to create permits to this area.",
                related_name="allowed_permit_areas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="allowed users",
            ),
        ),
    ]
