# Generated by Django 2.2.15 on 2023-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parkings", "0047_populate_permitarea_allowed_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permitarea",
            name="permitted_user",
        ),
    ]
