name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.8", "3.9", "3.10"]
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{matrix.python}}
        uses: actions/setup-python@v3.1.2
        with:
          python-version: ${{matrix.python}}

      - name: Install Tox and tox-gh-actions
        run: pip install tox tox-gh-actions

      - name: Test with Tox
        run: tox
