name: "Tests and Checks"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: "Tests (Python ${{matrix.python}}, Django ${{matrix.django}})"
    strategy:
      matrix:
        python: ["3.10", "3.12", "3.14"]
        django: ["4.2", "5.2", "6.0"]
        exclude:
          - {python: "3.10", django: "6.0"}
          - {python: "3.14", django: "4.2"}
    runs-on: ubuntu-24.04
    container: "python:${{matrix.python}}-slim-trixie"
    steps:
      - uses: actions/checkout@v6

      - name: Update apt-get sources
        run: apt-get update

      - name: Install PostgreSQL, PostGIS and GDAL
        run: >
          apt-get install -y
          gdal-bin
          python3-gdal
          postgis
          postgresql
          postgresql-client
          postgresql-postgis
          libpq-dev
          build-essential

      - name: Start PostgreSQL server
        run: /etc/init.d/postgresql start

      - name: Allow root to create PostgreSQL databases
        run: su - postgres -c "createuser --createdb root"

      - name: Create PostGIS extension
        run: >
          su - postgres
          -c "psql template1 -c 'create extension postgis'"

      - name: Install Tox and tox-uv
        run: pip install tox tox-uv

      - name: Set TOXENV
        run: >-
          echo "TOXENV=py${{matrix.python}}-django${{matrix.django}}"
          | tr -d . >> $GITHUB_ENV

      - name: Test with Tox
        run: tox
        env:
          TOXENV: ${{env.TOXENV}}

      - name: Install git and curl for codecov action
        run: apt-get install -y git curl

      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  test-dockerization:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image of the app
        run: docker compose build

      - name: Start the services with docker compose up
        run: docker compose up -d

      - name: Run pytest in the app container
        run: USE_DOCKER=1 ./run-pytest -vvv

  checks:
    strategy:
      matrix:
        toxenv: [style, check, uvlock, sanitizer]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install GDAL
        run: sudo apt-get update && sudo apt-get install -y gdal-bin
        if: ${{ contains(fromJSON('["check", "sanitizer"]'), matrix.toxenv) }}

      - name: Install Tox and tox-uv
        run: pip install tox tox-uv

      - name: Run the check with Tox
        run: tox
        env:
          TOXENV: ${{matrix.toxenv}}

  dashboard:
    strategy:
      matrix:
        check: [build, tests]
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: dashboard
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10"

      - name: Install dashboard dependencies
        run: pnpm i

      - name: Build dashboard
        if: ${{ matrix.check == 'build' }}
        run: pnpm build

      - name: Test dashboard
        if: ${{ matrix.check == 'tests' }}
        run: pnpm test --run
